export default {
  "title": "Vue BOBuilder",
  "tagline": "Autogenerated admin from simple JSON config and REST API connected",
  "url": "https://JeremyDolle.github.com",
  "baseUrl": "/VuejsBOBuilder/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/logo.PNG",
  "organizationName": "JeremyDolle",
  "projectName": "VuejsBOBuilder",
  "themeConfig": {
    "navbar": {
      "title": "Vue BOBuilder",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/logo.PNG"
      },
      "items": [
        {
          "to": "docs/Introduction",
          "activeBasePath": "docs",
          "label": "Docs",
          "position": "left"
        },
        {
          "href": "https://github.com/JeremyDolle/VuejsBOBuilder",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Vue BOBuilder logo",
        "src": "img/logo.png"
      },
      "copyright": "Copyright © 2020 JeremyDolle, Inc. Built with Docusaurus.",
      "links": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false,
      "switchConfig": {
        "darkIcon": "🌜",
        "darkIconStyle": {},
        "lightIcon": "🌞",
        "lightIconStyle": {}
      }
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadatas": [],
    "prism": {
      "additionalLanguages": []
    },
    "hideableSidebar": false
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/jeremydolle/Documents/PROJETS/PERSO/VuejsBOBuilder/documentation/sidebars.js",
          "editUrl": "https://github.com/JeremyDolle/VuejsBOBuilder/tree/documentation/documentation/docs"
        },
        "theme": {
          "customCss": "/Users/jeremydolle/Documents/PROJETS/PERSO/VuejsBOBuilder/documentation/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "plugins": [],
  "themes": [],
  "titleDelimiter": "|",
  "noIndex": false
};