module.exports = {
  title: 'Vue BOBuilder',
  tagline: 'Autogenerated admin from simple JSON config and REST API connected',
  url: 'https://JeremyDolle.github.com',
  baseUrl: '/VuejsBOBuilder/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/logo.PNG',
  organizationName: 'JeremyDolle', // Usually your GitHub org/user name.
  projectName: 'VuejsBOBuilder', // Usually your repo name.
  themeConfig: {
    navbar: {
      title: 'Vue BOBuilder',
      logo: {
        alt: 'My Site Logo',
        src: 'img/logo.PNG',
      },
      items: [
        {
          to: 'docs/Introduction',
          activeBasePath: 'docs',
          label: 'Docs',
          position: 'left',
        },
        {
          href: 'https://github.com/JeremyDolle/VuejsBOBuilder',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      logo: {
        alt: 'Vue BOBuilder logo',
        src: 'img/TOM.png',
      },
      copyright: `Copyright © ${new Date().getFullYear()} JeremyDolle, Inc. Built with Docusaurus.`,
    },
  },
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          editUrl:
            'https://github.com/JeremyDolle/VuejsBOBuilder/tree/documentation/documentation/docs',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
};
